server.port=8080
nasa.api.key=${NASA_API_KEY:BnJVPiHXWagRnLcEo6PqC4h0wwpFS6Zr8YvrQqKt}
nasa.api.base-url=${NASA_API_BASE_URL:https://api.nasa.gov/planetary/apod}
openrouter.api.key=${OPENROUTER_API_KEY:}
openrouter.model=deepseek/deepseek-chat
